# Generated by Django 5.1.5 on 2025-02-02 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='questionPaperImage/')),
                ('year', models.IntegerField()),
                ('semester', models.PositiveIntegerField(default=1)),
                ('subject', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
            ],
        ),
    ]
